version: "3"

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "teste"
      POSTGRES_USER: "teste"
      POSTGRES_PASSWORD: "teste"
      PGDATA: "/tempDB"
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge
