version: "3"

services:
  apis:
    image: apis:local
    restart: "always"
    env_file:
      - docker-compose.env
    ports:
      - "8098:8098"

  postgres_db:
    image: postgres
    environment:
      POSTGRES_DB: "teste"
      POSTGRES_USER: "teste"
      POSTGRES_PASSWORD: "teste"
      PGDATA: "/tempDB"
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge
