// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CompleteTransactionService is an autogenerated mock type for the CompleteTransactionService type
type CompleteTransactionService struct {
	mock.Mock
}

// Complete provides a mock function with given fields: transactionID
func (_m *CompleteTransactionService) Complete(transactionID string) error {
	ret := _m.Called(transactionID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(transactionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCompleteTransactionService interface {
	mock.TestingT
	Cleanup(func())
}

// NewCompleteTransactionService creates a new instance of CompleteTransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCompleteTransactionService(t mockConstructorTestingTNewCompleteTransactionService) *CompleteTransactionService {
	mock := &CompleteTransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
