// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	_interfaces "pedroprado.transaction.api/src/core/_interfaces"
	entity "pedroprado.transaction.api/src/core/domain/entity"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: transaction
func (_m *TransactionRepository) Create(transaction entity.Transaction) (*entity.Transaction, error) {
	ret := _m.Called(transaction)

	var r0 *entity.Transaction
	if rf, ok := ret.Get(0).(func(entity.Transaction) *entity.Transaction); ok {
		r0 = rf(transaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.Transaction) error); ok {
		r1 = rf(transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: transactionID
func (_m *TransactionRepository) Get(transactionID string) (*entity.Transaction, error) {
	ret := _m.Called(transactionID)

	var r0 *entity.Transaction
	if rf, ok := ret.Get(0).(func(string) *entity.Transaction); ok {
		r0 = rf(transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLock provides a mock function with given fields: transactionID
func (_m *TransactionRepository) GetLock(transactionID string) (*entity.Transaction, error) {
	ret := _m.Called(transactionID)

	var r0 *entity.Transaction
	if rf, ok := ret.Get(0).(func(string) *entity.Transaction); ok {
		r0 = rf(transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithTransaction provides a mock function with given fields: tx
func (_m *TransactionRepository) WithTransaction(tx *gorm.DB) _interfaces.TransactionRepository {
	ret := _m.Called(tx)

	var r0 _interfaces.TransactionRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) _interfaces.TransactionRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(_interfaces.TransactionRepository)
		}
	}

	return r0
}

type mockConstructorTestingTNewTransactionRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionRepository(t mockConstructorTestingTNewTransactionRepository) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
