// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entity "pedroprado.transaction.api/src/core/domain/entity"
)

// TransactionStatusService is an autogenerated mock type for the TransactionStatusService type
type TransactionStatusService struct {
	mock.Mock
}

// Create provides a mock function with given fields: transactionStatus
func (_m *TransactionStatusService) Create(transactionStatus entity.TransactionStatus) (*entity.TransactionStatus, error) {
	ret := _m.Called(transactionStatus)

	var r0 *entity.TransactionStatus
	if rf, ok := ret.Get(0).(func(entity.TransactionStatus) *entity.TransactionStatus); ok {
		r0 = rf(transactionStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TransactionStatus)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.TransactionStatus) error); ok {
		r1 = rf(transactionStatus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByTransactionID provides a mock function with given fields: transactionID
func (_m *TransactionStatusService) FindByTransactionID(transactionID string) (*entity.TransactionStatus, error) {
	ret := _m.Called(transactionID)

	var r0 *entity.TransactionStatus
	if rf, ok := ret.Get(0).(func(string) *entity.TransactionStatus); ok {
		r0 = rf(transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TransactionStatus)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: transactionStatus
func (_m *TransactionStatusService) Update(transactionStatus entity.TransactionStatus) (*entity.TransactionStatus, error) {
	ret := _m.Called(transactionStatus)

	var r0 *entity.TransactionStatus
	if rf, ok := ret.Get(0).(func(entity.TransactionStatus) *entity.TransactionStatus); ok {
		r0 = rf(transactionStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TransactionStatus)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.TransactionStatus) error); ok {
		r1 = rf(transactionStatus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTransactionStatusService interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionStatusService creates a new instance of TransactionStatusService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionStatusService(t mockConstructorTestingTNewTransactionStatusService) *TransactionStatusService {
	mock := &TransactionStatusService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
