// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entity "pedroprado.transaction.api/src/core/domain/entity"
)

// TransactionService is an autogenerated mock type for the TransactionService type
type TransactionService struct {
	mock.Mock
}

// CompensateTransaction provides a mock function with given fields: transactionID
func (_m *TransactionService) CompensateTransaction(transactionID string) (*entity.Transaction, error) {
	ret := _m.Called(transactionID)

	var r0 *entity.Transaction
	if rf, ok := ret.Get(0).(func(string) *entity.Transaction); ok {
		r0 = rf(transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompleteTransaction provides a mock function with given fields: transactionID
func (_m *TransactionService) CompleteTransaction(transactionID string) (*entity.Transaction, error) {
	ret := _m.Called(transactionID)

	var r0 *entity.Transaction
	if rf, ok := ret.Get(0).(func(string) *entity.Transaction); ok {
		r0 = rf(transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTransaction provides a mock function with given fields: transaction
func (_m *TransactionService) CreateTransaction(transaction entity.Transaction) (*entity.Transaction, error) {
	ret := _m.Called(transaction)

	var r0 *entity.Transaction
	if rf, ok := ret.Get(0).(func(entity.Transaction) *entity.Transaction); ok {
		r0 = rf(transaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.Transaction) error); ok {
		r1 = rf(transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: transactionID
func (_m *TransactionService) Get(transactionID string) (*entity.Transaction, error) {
	ret := _m.Called(transactionID)

	var r0 *entity.Transaction
	if rf, ok := ret.Get(0).(func(string) *entity.Transaction); ok {
		r0 = rf(transactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTransactionService interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionService creates a new instance of TransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionService(t mockConstructorTestingTNewTransactionService) *TransactionService {
	mock := &TransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
